# Etapa 1: Builder
FROM node:18 AS builder

# Definir o diretório de trabalho
WORKDIR /app

# Copiar os arquivos de dependência para o container
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar todo o código para o container
COPY . .

# Compilar o código TypeScript para JavaScript
RUN npm run build

# Etapa 2: Final
FROM node:18

# Definir o diretório de trabalho
WORKDIR /app

# Copiar as dependências instaladas da etapa anterior
COPY --from=builder /app/node_modules ./node_modules

# Copiar a pasta compilada da etapa anterior
COPY --from=builder /app/dist ./dist

# Copiar os arquivos necessários para a execução
COPY package*.json ./

# Definir a porta que o aplicativo vai expor
EXPOSE 3000

# Comando de inicialização do aplicativo
CMD ["node", "dist/main"]
